### ISSUE TITLE
unable to register to forum via github.

### ISSUE THREAD

**Issue by dkebler** [vuejs/vuejs.org#685] opened 2017-01-06 04:03 UTC
never got to the github authorization page.  this is what comes up immediately after clicking the signup with github button.  Sorry this is probably not the right place to bring up this issue, but catch 22 I can't sign up to the forum to do so. :-).

![image](https://cloud.githubusercontent.com/assets/1316185/21707161/c7157b1a-d381-11e6-8e25-0cce1c9fcd40.png)

**Comment by chrisvfritz** [comment] 2017-01-07 05:35
I agree this is probably the best place to post this given your situation! I believe @LinusBorg is already aware of and investigating this problem, so I'll bring him into the conversation.

**Comment by dkebler** [comment] 2017-01-09 17:55
thx,  just so you know I've successfully used my github credential at many other sites so it's not specific to me.  And I just checked...I'm still getting the same error

**Comment by chrisvfritz** [comment] 2017-01-09 22:33
Yes, there's definitely an issue on our end. We just have to figure out why it's failing for some people.

**Comment by phanan** [comment] 2017-01-14 18:16
Meanwhile @dkebler you can use the reset password feature to log into the forum again – just use the same password. That's what I did, as a workaround.

**Comment by sqal** [comment] 2017-01-17 17:06
I think it's fixed now, ref: https://github.com/vuejs/vue/issues/4734

**Comment by znck** [comment] 2017-01-18 04:18
The issue is fixed. If it persists for you, you can reopen the issue.

**Closed by znck** 2017-01-18 04:18 UTC
Labels: bug

**Comment by dkebler** [comment] 2017-02-03 17:40
Yes I can confirm it is fixed.  I was finally able to register via github credential.  Thx!
