### ISSUE TITLE
Not using images in documentation for displaying code

### ISSUE THREAD

**Issue by goelrohan6** [vuejs/vuejs.org#1669] opened 2018-06-04 08:16 UTC
I guess it will be better to just write the code than embedding images of it, like in https://github.com/vuejs/vuejs.org/blob/master/src/v2/guide/single-file-components.md
It's easier to view or copy, image feels abrupt and opens a gist on click which kind of breaks the flow.

Thoughts?

**Comment by chrisvfritz** [comment] 2018-06-04 16:54
This looks like a duplicate of #1650. I explain there why we decided to use images in this case and recently added the Gists as a compromise. Feel free to add your thoughts there.

**Closed by chrisvfritz** 2018-06-04 16:54 UTC
