### ISSUE TITLE
Spanish (BO) Translation "work-in-progress" 

### ISSUE THREAD

**Issue by joelTorrejon** [vuejs/vuejs.org#1004] opened 2017-07-10 22:18 UTC
Hi guys, I started the Spanish version of the documentation, I will try to do my best and upload changes permanently. :smiley: 

So, I created:
- New organization: https://github.com/vuejs-bo
- New repo: https://github.com/vuejs-bo/vuejs.org

I will take the documentation as priority and I hope this helps the community.

**Comment by chrisvfritz** [comment] 2017-07-10 23:37
Sounds great! Let me know if you have any questions. 🙂

**Comment by joelTorrejon** [comment] 2017-07-10 23:44
Ok, i will try to organize the advance and i will report weekly :+1:

**Comment by zeratulmdq** [comment] 2017-07-11 15:59
@chrisvfritz while I guess it's (kind of) ok if you wanna close #308 I think the work should be done there. With @posva we agreed that the translation was a three step process.

1. Translate the file
2. Review the translation
3. Review the review.

The entire translation is almost complete [as you can see here](https://github.com/es-vuejs/vuejs.org/issues/3) the problem is I'm working alone and nobody is reviewing my translations. It's not active because there's no one willing to do the "dirty" work and I'm stuck. If you start over, the same thing will happen again. 

I've translated vue-router (and it's up to date) and I've contributed to this repos' site (to make new translations easier), I take documentation/translation seriously.

Cheers!

**Comment by chrisvfritz** [comment] 2017-07-11 20:01
@zeratulmdq Thanks for updating me! I didn't know the work was continuing. It sounds like @joelTorrejon can help you then. I'll reopen that issue and close this one.

**Closed by chrisvfritz** 2017-07-11 20:01 UTC
Labels: 2.0, community translation

**Comment by joelTorrejon** [comment] 2017-07-11 20:37
Ok, no problem. I will work with them :+1:
