### ISSUE TITLE
List move transitions are missing transition CSS styles

### ISSUE THREAD

**Issue by fsaenger** [vuejs/vuejs.org#1215] opened 2017-10-13 14:24 UTC
The examples in the Guide under [List Move Transitions](https://vuejs.org/v2/guide/transitions.html#List-Move-Transitions) are not working the way that I'm guessing they should – at least compared to how these examples are described in the text.

This is what the first example looks like (showing no transition at all), but the lazy sudoku isn't working either:

![list-move-test](https://user-images.githubusercontent.com/2722264/31550529-26616a4a-b08e-11e7-940e-e02ec7e13019.gif)

From what I can tell, they are missing the relevant CSS styles to define start and end of their transition states.

**Comment by chrisvfritz** [comment] 2017-10-13 15:28
Strange, they're working on my end. Can you share the browser you're using?

**Comment by fsaenger** [comment] 2017-10-13 15:35
I started in Safari 11.0, but Firefox 56.0 and Chrome 61.0 aren't working either.

All on macOS 10.13.

**Comment by chrisvfritz** [comment] 2017-10-13 16:10
@fsaenger Thanks! I just started seeing it too. Investigating now.

**Comment by chrisvfritz** [comment] 2017-10-13 17:44
It turned out to be a regression in v2.5.0, now fixed in v2.5.1. Thanks for the report!

**Closed by chrisvfritz** 2017-10-13 17:44 UTC

**Comment by fsaenger** [comment] 2017-10-14 11:39
👌

Sorry about the very vague bug report through, I’m not yet familiar enough with Vue to debug that myself.

**Comment by chrisvfritz** [comment] 2017-10-14 16:56
Nothing to be sorry about! 🙂  You provided all the information I needed to replicate the issue and start hunting down the cause.
