### ISSUE TITLE
example page contains error on ipad

### ISSUE THREAD

**Issue by ZaynJarvis** [vuejs/vuejs.org#1889] opened 2018-11-26 05:24 UTC
When double tap to enlarge the view on iPad, the example page "example header" position changes and is not clickable.
![image](https://user-images.githubusercontent.com/31875147/48994496-9010e600-f17e-11e8-982e-7b082bd3f44a.png)

**Comment by phanan** [comment] 2019-01-28 17:53
Thanks for reporting the issue. I can't reproduce it though, and would argue that it would be an edge case anyway, so I'm closing this. Feel free to open another if you don't think so.

**Closed by phanan** 2019-01-28 17:53 UTC
