### ISSUE TITLE
Add comparison to Svelte

### ISSUE THREAD

**Issue by richardtallent** [vuejs/vuejs.org#668] opened 2016-12-24 17:37 UTC
I'm trying out various frameworks and libraries for several new projects, and really appreciate the page on Vue's site comparing it to other alternatives.

Since I've been focused primarily on Riot, the comparison to it was especially useful. But while I enjoy working in Riot, I've run into some frustrations around the very limited template language, especially the inherent limitations of attribute-based conditionals and loops (vs. actual blocks that can contain multiple elements).

I've been looking at Svelte as an alternative and really like both it's syntax for conditionals and loops in templates and its approach of pre-compiling templates to plain old Javascript. Since I'm new to Vue, I'd love to read some opinions from people familiar with both about how they compare.

**Comment by chrisvfritz** [comment] 2016-12-24 18:40
I'm not an expert on Svelte, but it seems to share a lot of design philosophies with Vue, which I really enjoyed. I think the feature that makes it stand out for most people is that is compiles itself away. That's a really interesting idea and I can recommend browsing the source as an educational opportunity, but I don't see the feature itself as more than a gimmick right now. In the applications large enough to really start worrying about the size, Vue itself will already be such a small part of the total build.

Some other noteworthy differences:

- Svelte has no render functions (and I believe by design cannot?), while Vue supports both templates and render functions
- Unsurprisingly since it's so young, Svelte isn't as battle-tested as Vue and its ecosystem is still very immature. In China particularly, I think it was once estimated that half of the $1+ billion tech companies in the country were using Vue in some capacity. Don't quote me on that exactly, but the point is, Vue has proven itself at every scale.

I hope that helps and I apologize if any part is inaccurate. I'm sure there are also many other differences, but that's off the top of my head.

**Comment by chrisvfritz** [comment] 2017-07-10 00:05
Closing for now, as Svelte might still be a little too niche to spend time on a comparison. 🙂

**Closed by chrisvfritz** 2017-07-10 00:05 UTC
Labels: enhancement

**Comment by stalkerg** [comment] 2018-03-26 06:46
In my opinion Svelte right now is not a niche solution. It's very close to Vue but much faster, and for several projects, I choose Svelte (and for future too).

**Comment by loopmode** [comment] 2018-04-03 12:17
https://javascriptreport.com/vue-and-svelte-a-lot-alike-but-some-important-differences/
