### ISSUE TITLE
Become a sponsor button not working

### ISSUE THREAD

**Issue by AlejandroMut** [vuejs/vuejs.org#1687] opened 2018-06-14 18:09 UTC
The "Become a sponsor" buttons are linking to a broken page: https://opencollective.com/vuejs/tiers/gold-sponsors/7/website

**Comment by cukejianya** [comment] 2018-06-19 18:52
This is is a problem with open collective and is being worked on. https://github.com/opencollective/opencollective/issues/1127

**Comment by phanan** [comment] 2019-01-28 17:44
Closing as the issue is no longer valid. Thank you!

**Closed by phanan** 2019-01-28 17:44 UTC
